# Generated by Django 5.2.6 on 2025-09-24 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSavingsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members_count', models.IntegerField(default=0)),
                ('savings_to_date', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('formation_date', models.DateField()),
                ('meeting_day', models.CharField(blank=True, max_length=20)),
                ('meeting_location', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'upg_business_savings_groups',
            },
        ),
        migrations.CreateModel(
            name='BSGProgressSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_date', models.DateField()),
                ('saving_last_month', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('month_recorded', models.DateField()),
                ('attendance_this_meeting', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('surveyor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bsg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_surveys', to='savings_groups.businesssavingsgroup')),
            ],
            options={
                'db_table': 'upg_bsg_progress_surveys',
            },
        ),
        migrations.CreateModel(
            name='BSGMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chairperson', 'Chairperson'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_date', models.DateField()),
                ('total_savings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household')),
                ('bsg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bsg_members', to='savings_groups.businesssavingsgroup')),
            ],
            options={
                'db_table': 'upg_bsg_members',
            },
        ),
    ]
