# Generated by Django 5.2.6 on 2025-09-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssavingsgroup',
            name='target_members',
            field=models.IntegerField(default=25, help_text='Target number of members for this savings group'),
        ),
    ]
