# Generated by Django 5.2.6 on 2025-10-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_groups', '0001_initial'),
        ('savings_groups', '0002_businesssavingsgroup_target_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssavingsgroup',
            name='business_groups',
            field=models.ManyToManyField(blank=True, help_text='Business groups that are part of this savings group', related_name='savings_groups', to='business_groups.businessgroup'),
        ),
    ]
