# Generated by Django 5.2.6 on 2025-10-02 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_groups', '0003_businesssavingsgroup_business_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssavingsgroup',
            name='savings_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly')], default='weekly', help_text='How often members save', max_length=20),
        ),
        migrations.CreateModel(
            name='SavingsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('savings_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bsg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_records', to='savings_groups.businesssavingsgroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_records', to='savings_groups.bsgmember')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upg_savings_records',
                'ordering': ['-savings_date', '-created_at'],
            },
        ),
    ]
