# Generated by Django 5.2.6 on 2025-09-26 04:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_groups', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SBGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant_amount', models.DecimalField(decimal_places=2, default=Decimal('15000.00'), max_digits=10)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Application'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('disbursement_status', models.CharField(choices=[('not_disbursed', 'Not Disbursed'), ('partially_disbursed', 'Partially Disbursed'), ('fully_disbursed', 'Fully Disbursed')], default='not_disbursed', max_length=20)),
                ('business_plan', models.TextField(help_text='Business plan submitted with application')),
                ('projected_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('utilization_report', models.TextField(blank=True)),
                ('utilization_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sb_grants', to=settings.AUTH_USER_MODEL)),
                ('business_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sb_grant', to='business_groups.businessgroup')),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_sb_grants', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sb_grants', to='programs.program')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sb_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SB Grant (Seed Business)',
                'verbose_name_plural': 'SB Grants (Seed Business)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PRGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant_amount', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=10)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('not_eligible', 'Not Eligible Yet'), ('eligible', 'Eligible'), ('pending', 'Pending Application'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='not_eligible', max_length=20)),
                ('performance_score', models.IntegerField(blank=True, help_text='Performance score 0-100', null=True)),
                ('performance_rating', models.CharField(blank=True, choices=[('excellent', 'Excellent Performance'), ('good', 'Good Performance'), ('satisfactory', 'Satisfactory Performance'), ('poor', 'Poor Performance')], max_length=20)),
                ('performance_assessment', models.TextField(blank=True, help_text='Detailed performance assessment')),
                ('revenue_generated', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('jobs_created', models.PositiveIntegerField(default=0)),
                ('savings_accumulated', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pr_grants', to=settings.AUTH_USER_MODEL)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_pr_grants', to=settings.AUTH_USER_MODEL)),
                ('business_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pr_grant', to='business_groups.businessgroup')),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_pr_grants', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr_grants', to='programs.program')),
                ('sb_grant', models.OneToOneField(help_text='PR grants are only available after SB grant', on_delete=django.db.models.deletion.CASCADE, related_name='pr_grant', to='upg_grants.sbgrant')),
            ],
            options={
                'verbose_name': 'PR Grant (Performance Recognition)',
                'verbose_name_plural': 'PR Grants (Performance Recognition)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrantDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disbursement_type', models.CharField(choices=[('sb_grant', 'SB Grant'), ('pr_grant', 'PR Grant')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disbursement_date', models.DateField()),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash'), ('check', 'Check')], default='bank_transfer', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_contact', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_disbursements', to=settings.AUTH_USER_MODEL)),
                ('pr_grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='upg_grants.prgrant')),
                ('sb_grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='upg_grants.sbgrant')),
            ],
            options={
                'ordering': ['-disbursement_date'],
            },
        ),
    ]
