# Generated by Django 5.2.6 on 2025-09-26 23:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upg_grants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbgrant',
            name='grant_amount',
        ),
        migrations.AddField(
            model_name='sbgrant',
            name='base_grant_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('15000.00'), help_text='Base grant amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='sbgrant',
            name='business_type_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplier based on business type', max_digits=3),
        ),
        migrations.AddField(
            model_name='sbgrant',
            name='calculated_grant_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated based on criteria', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sbgrant',
            name='final_grant_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final approved amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sbgrant',
            name='group_size_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplier based on group size', max_digits=3),
        ),
        migrations.AddField(
            model_name='sbgrant',
            name='location_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Geographic location adjustment', max_digits=3),
        ),
        migrations.AddField(
            model_name='sbgrant',
            name='monthly_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Projected monthly expenses', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sbgrant',
            name='performance_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Based on group performance', max_digits=3),
        ),
        migrations.AddField(
            model_name='sbgrant',
            name='startup_costs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated startup costs', max_digits=10, null=True),
        ),
    ]
