# Generated by Django 5.2.6 on 2025-10-01 18:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_groups', '0001_initial'),
        ('households', '0004_household_subcounty'),
        ('programs', '0001_initial'),
        ('upg_grants', '0002_remove_sbgrant_grant_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sbgrant',
            name='household',
            field=models.ForeignKey(blank=True, help_text='For individual household applications', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sb_grants', to='households.household'),
        ),
        migrations.AddField(
            model_name='sbgrant',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted the application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_sb_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sbgrant',
            name='business_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sb_grant', to='business_groups.businessgroup'),
        ),
        migrations.CreateModel(
            name='HouseholdGrantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant_type', models.CharField(choices=[('seed_business', 'Seed Business Grant'), ('livelihood', 'Livelihood Grant'), ('emergency', 'Emergency Grant'), ('education', 'Education Support Grant'), ('housing', 'Housing Improvement Grant'), ('other', 'Other')], max_length=20)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('title', models.CharField(help_text='Brief title of grant purpose', max_length=200)),
                ('purpose', models.TextField(help_text='Detailed purpose and justification for the grant')),
                ('business_plan', models.TextField(blank=True, help_text='Business plan if applicable')),
                ('expected_outcomes', models.TextField(help_text='Expected outcomes and impact')),
                ('budget_breakdown', models.JSONField(blank=True, default=dict, help_text='Itemized budget as JSON')),
                ('supporting_documents', models.JSONField(blank=True, default=list, help_text='List of document paths')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('review_score', models.IntegerField(blank=True, help_text='Review score 0-100', null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('disbursement_method', models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash'), ('check', 'Check')], max_length=50)),
                ('disbursement_reference', models.CharField(blank=True, max_length=100)),
                ('utilization_report', models.TextField(blank=True, help_text='How the grant was utilized')),
                ('utilization_date', models.DateField(blank=True, null=True)),
                ('final_outcomes', models.TextField(blank=True, help_text='Final outcomes achieved')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_household_grants', to=settings.AUTH_USER_MODEL)),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_household_grants', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_applications', to='households.household')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_grant_applications', to='programs.program')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_household_grants', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(help_text='User who submitted the application', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_grant_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Household Grant Application',
                'verbose_name_plural': 'Household Grant Applications',
                'db_table': 'upg_household_grant_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
