# Generated by Django 5.2.6 on 2025-10-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upg_grants', '0003_sbgrant_household_sbgrant_submitted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdgrantapplication',
            name='grant_type',
            field=models.CharField(choices=[('seed_business', 'Seed Business Grant'), ('performance_recognition', 'Performance Recognition Grant'), ('livelihood', 'Livelihood Grant'), ('emergency', 'Emergency Grant'), ('education', 'Education Support Grant'), ('housing', 'Housing Improvement Grant'), ('other', 'Other')], max_length=30),
        ),
    ]
