# Generated by Django 5.2.6 on 2025-10-01 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('upg_grants', '0004_alter_householdgrantapplication_grant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdgrantapplication',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Optional - for program-specific funding', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='household_grant_applications', to='programs.program'),
        ),
    ]
