# Generated by Django 5.2.6 on 2025-10-02 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_groups', '0001_initial'),
        ('households', '0005_household_constituency_household_district_and_more'),
        ('savings_groups', '0003_businesssavingsgroup_business_groups'),
        ('upg_grants', '0005_alter_householdgrantapplication_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdgrantapplication',
            name='business_group',
            field=models.ForeignKey(blank=True, help_text='For business group applications', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grant_applications', to='business_groups.businessgroup'),
        ),
        migrations.AddField(
            model_name='householdgrantapplication',
            name='savings_group',
            field=models.ForeignKey(blank=True, help_text='For savings group applications', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grant_applications', to='savings_groups.businesssavingsgroup'),
        ),
        migrations.AddField(
            model_name='prgrant',
            name='household',
            field=models.ForeignKey(blank=True, help_text='For individual household applications', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_grants', to='households.household'),
        ),
        migrations.AddField(
            model_name='prgrant',
            name='savings_group',
            field=models.ForeignKey(blank=True, help_text='For savings group applications', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_grants', to='savings_groups.businesssavingsgroup'),
        ),
        migrations.AddField(
            model_name='sbgrant',
            name='savings_group',
            field=models.ForeignKey(blank=True, help_text='For savings group applications', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sb_grants', to='savings_groups.businesssavingsgroup'),
        ),
        migrations.AlterField(
            model_name='householdgrantapplication',
            name='household',
            field=models.ForeignKey(blank=True, help_text='For individual household applications', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grant_applications', to='households.household'),
        ),
        migrations.AlterField(
            model_name='prgrant',
            name='business_group',
            field=models.OneToOneField(blank=True, help_text='For business group applications', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_grant', to='business_groups.businessgroup'),
        ),
        migrations.AlterField(
            model_name='sbgrant',
            name='business_group',
            field=models.OneToOneField(blank=True, help_text='For business group applications', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sb_grant', to='business_groups.businessgroup'),
        ),
    ]
