# Generated by Django 5.2.6 on 2025-09-26 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_groups', '0001_initial'),
        ('households', '0002_upgmilestone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('direct_to_mentor', 'Direct to Mentor'), ('via_field_associate', 'Via Field Associate')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_villages', models.JSONField(blank=True, default=list)),
                ('target_households', models.JSONField(blank=True, default=list)),
                ('target_business_groups', models.JSONField(blank=True, default=list)),
                ('min_submissions_required', models.IntegerField(default=1)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('field_associate', models.ForeignKey(blank=True, limit_choices_to={'role': 'field_associate'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_forms', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(blank=True, limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_forms_mentor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upg_form_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('form_type', models.CharField(choices=[('household_survey', 'Household Survey'), ('business_survey', 'Business Progress Survey'), ('ppi_assessment', 'PPI Assessment'), ('baseline_survey', 'Baseline Survey'), ('midline_survey', 'Midline Survey'), ('endline_survey', 'Endline Survey'), ('training_evaluation', 'Training Evaluation'), ('mentoring_report', 'Mentoring Report'), ('custom_form', 'Custom Form')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('form_fields', models.JSONField(default=list, help_text='JSON structure defining form fields')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_multiple_submissions', models.BooleanField(default=False)),
                ('require_photo_evidence', models.BooleanField(default=False)),
                ('require_gps_location', models.BooleanField(default=False)),
                ('auto_assign_to_mentors', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upg_form_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('form_data', models.JSONField(default=dict)),
                ('photo_evidence', models.ImageField(blank=True, null=True, upload_to='form_submissions/photos/')),
                ('document_attachment', models.FileField(blank=True, null=True, upload_to='form_submissions/docs/')),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.formassignment')),
                ('business_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_groups.businessgroup')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='households.household')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formtemplate')),
            ],
            options={
                'db_table': 'upg_form_submissions',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('number', 'Number Input'), ('email', 'Email Input'), ('phone', 'Phone Number'), ('date', 'Date Picker'), ('datetime', 'Date & Time'), ('select', 'Dropdown Select'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkboxes'), ('boolean', 'Yes/No'), ('file', 'File Upload'), ('image', 'Image Upload'), ('rating', 'Rating Scale'), ('location', 'GPS Location'), ('signature', 'Digital Signature')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('default_value', models.CharField(blank=True, max_length=500)),
                ('choices', models.JSONField(blank=True, default=list, help_text='List of choices for select/radio/checkbox fields')),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('validation_regex', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('show_if_field', models.CharField(blank=True, help_text='Show this field only if another field has specific value', max_length=100)),
                ('show_if_value', models.CharField(blank=True, max_length=200)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.formtemplate')),
            ],
            options={
                'db_table': 'upg_form_fields',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='formassignment',
            name='form_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='forms.formtemplate'),
        ),
        migrations.CreateModel(
            name='FormAssignmentMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('instructions', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('assigned_by_fa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fa_mentor_assignments', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='forms.formassignment')),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upg_form_assignment_mentors',
                'unique_together': {('assignment', 'mentor')},
            },
        ),
    ]
