# Generated by Django 5.2.6 on 2025-09-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_smslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='distance_to_market',
            field=models.IntegerField(default=0, help_text='Distance to market in kilometers'),
        ),
        migrations.AddField(
            model_name='village',
            name='is_program_area',
            field=models.BooleanField(default=True, help_text='Whether this village is in a program target area'),
        ),
    ]
