# Generated by Django 5.2.6 on 2025-10-01 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_village_distance_to_market_village_is_program_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(default='Kenya', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'db_table': 'upg_counties',
            },
        ),
        migrations.AlterField(
            model_name='village',
            name='saturation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='village',
            name='subcounty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcounties', to='core.county')),
            ],
            options={
                'verbose_name_plural': 'Sub-Counties',
                'db_table': 'upg_subcounties',
                'unique_together': {('name', 'county')},
            },
        ),
        migrations.AddField(
            model_name='village',
            name='subcounty_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='core.subcounty'),
        ),
    ]
