# Generated by Django 5.2.6 on 2025-10-02 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_county_alter_village_saturation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='subcounty',
        ),
    ]
