# Generated by Django 5.2.6 on 2025-09-25 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('maintenance', 'Maintenance'), ('security', 'Security')], default='info', max_length=20)),
                ('scope', models.CharField(choices=[('system', 'System Wide'), ('role', 'Role Specific'), ('user', 'User Specific')], default='system', max_length=20)),
                ('target_roles', models.JSONField(blank=True, default=list, help_text="List of roles if scope is 'role'")),
                ('is_active', models.BooleanField(default=True)),
                ('show_until', models.DateTimeField(blank=True, help_text='Alert expires after this date', null=True)),
                ('is_dismissible', models.BooleanField(default=True, help_text='Users can dismiss this alert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_alerts', to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(blank=True, help_text="Specific users if scope is 'user'", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upg_system_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('backup_type', models.CharField(choices=[('full', 'Full Backup'), ('incremental', 'Incremental Backup'), ('database', 'Database Only'), ('media', 'Media Files Only')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upg_system_backups',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Configuration key identifier', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Configuration value')),
                ('setting_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON'), ('file', 'File Path')], default='string', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of this setting')),
                ('category', models.CharField(default='general', help_text='Setting category', max_length=50)),
                ('is_public', models.BooleanField(default=False, help_text='Can be viewed by non-admin users')),
                ('is_editable', models.BooleanField(default=True, help_text='Can be modified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settings', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upg_system_configurations',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('dashboard_layout', models.JSONField(blank=True, default=dict)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', max_length=10)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upg_user_settings',
            },
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('import', 'Import'), ('system', 'System Action')], max_length=20)),
                ('model_name', models.CharField(blank=True, help_text='Django model name', max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='ID of the object acted upon', max_length=100)),
                ('object_repr', models.CharField(blank=True, help_text='String representation of the object', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Details of what changed')),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upg_system_audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='upg_system__user_id_429862_idx'), models.Index(fields=['action', 'timestamp'], name='upg_system__action_b12dc8_idx'), models.Index(fields=['model_name', 'timestamp'], name='upg_system__model_n_2e3843_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAlertDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_module.systemalert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upg_user_alert_dismissals',
                'unique_together': {('user', 'alert')},
            },
        ),
    ]
