# Generated by Django 5.2.6 on 2025-09-24 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_business_health', models.CharField(choices=[('red', 'Red - Poor Performance'), ('yellow', 'Yellow - Fair Performance'), ('green', 'Green - Good Performance')], default='yellow', max_length=10)),
                ('participation_status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('group_size', models.IntegerField(default=2)),
                ('business_type', models.CharField(choices=[('crop', 'Crop'), ('retail', 'Retail'), ('service', 'Service'), ('livestock', 'Livestock'), ('skill', 'Skill')], max_length=20)),
                ('business_type_detail', models.CharField(blank=True, max_length=100)),
                ('formation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program')),
            ],
            options={
                'db_table': 'upg_business_groups',
            },
        ),
        migrations.CreateModel(
            name='BusinessProgressSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_date', models.DateField()),
                ('grant_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grant_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('business_inputs', models.TextField(blank=True)),
                ('business_inventory', models.TextField(blank=True)),
                ('business_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_surveys', to='business_groups.businessgroup')),
                ('surveyor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upg_business_progress_surveys',
            },
        ),
        migrations.CreateModel(
            name='PRGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=20)),
                ('funding_status', models.CharField(choices=[('applied', 'Applied'), ('approved', 'Approved'), ('funded', 'Funded'), ('not_funded', 'Not Funded')], default='applied', max_length=20)),
                ('funded_date', models.DateField(blank=True, null=True)),
                ('grant_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leader_name', models.CharField(max_length=100)),
                ('treasurer_name', models.CharField(max_length=100)),
                ('secretary_name', models.CharField(max_length=100)),
                ('business_type_detail', models.CharField(blank=True, max_length=100)),
                ('why_pr_qualified', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr_grants', to='business_groups.businessgroup')),
            ],
            options={
                'db_table': 'upg_pr_grants',
            },
        ),
        migrations.CreateModel(
            name='SBGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=20)),
                ('funding_status', models.CharField(choices=[('applied', 'Applied'), ('approved', 'Approved'), ('funded', 'Funded'), ('not_funded', 'Not Funded')], default='applied', max_length=20)),
                ('funded_date', models.DateField(blank=True, null=True)),
                ('grant_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leader_name', models.CharField(max_length=100)),
                ('treasurer_name', models.CharField(max_length=100)),
                ('secretary_name', models.CharField(max_length=100)),
                ('business_type_detail', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sb_grants', to='business_groups.businessgroup')),
            ],
            options={
                'db_table': 'upg_sb_grants',
            },
        ),
        migrations.CreateModel(
            name='BusinessGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'Leader'), ('treasurer', 'Treasurer'), ('secretary', 'Secretary'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='business_groups.businessgroup')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household')),
            ],
            options={
                'db_table': 'upg_business_group_members',
                'unique_together': {('business_group', 'household')},
            },
        ),
    ]
