# Generated by Django 5.2.6 on 2025-09-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('county_executive', 'County Executive (CECM & Governor)'), ('county_assembly', 'County Assembly Member'), ('ict_admin', 'ICT Administrator'), ('me_staff', 'M&E Staff'), ('field_associate', 'Field Associate/Mentor Supervisor'), ('mentor', 'Mentor'), ('beneficiary', 'Beneficiary')], default='mentor', max_length=20),
        ),
    ]
