# Generated by Django 5.2.6 on 2025-09-24 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('disability', models.BooleanField(default=False)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.village')),
            ],
            options={
                'db_table': 'upg_households',
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('age', models.IntegerField()),
                ('relationship_to_head', models.CharField(choices=[('head', 'Head'), ('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=20)),
                ('education_level', models.CharField(choices=[('none', 'None'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], default='none', max_length=20)),
                ('is_program_participant', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='households.household')),
            ],
            options={
                'db_table': 'upg_household_members',
            },
        ),
        migrations.CreateModel(
            name='HouseholdSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_type', models.CharField(choices=[('baseline', 'Baseline'), ('midline', 'Midline'), ('endline', 'Endline')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('survey_date', models.DateField()),
                ('income_level', models.CharField(blank=True, max_length=50)),
                ('assets_owned', models.TextField(blank=True)),
                ('savings_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='households.household')),
                ('surveyor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upg_household_surveys',
            },
        ),
        migrations.CreateModel(
            name='PPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('eligibility_score', models.IntegerField()),
                ('assessment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppi_scores', to='households.household')),
            ],
            options={
                'db_table': 'upg_ppi',
            },
        ),
        migrations.CreateModel(
            name='HouseholdProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_status', models.CharField(choices=[('eligible', 'Eligible'), ('enrolled', 'Enrolled'), ('active', 'Active'), ('graduated', 'Graduated'), ('dropped_out', 'Dropped Out')], default='eligible', max_length=20)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('dropout_date', models.DateField(blank=True, null=True)),
                ('dropout_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_participations', to='households.household')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mentor')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program')),
            ],
            options={
                'db_table': 'upg_household_programs',
                'unique_together': {('household', 'program')},
            },
        ),
    ]
