# Generated by Django 5.2.6 on 2025-09-26 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UPGMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(choices=[('month_1', 'Month 1 - PPI Assessment & Business Training Start'), ('month_2', 'Month 2 - Business Group Formation'), ('month_3', 'Month 3 - Business Plan Development'), ('month_4', 'Month 4 - SB Grant Application'), ('month_5', 'Month 5 - SB Grant Disbursement'), ('month_6', 'Month 6 - Business Operations Start'), ('month_7', 'Month 7 - Mid-term Assessment'), ('month_8', 'Month 8 - Business Savings Group Formation'), ('month_9', 'Month 9 - PR Grant Eligibility Assessment'), ('month_10', 'Month 10 - PR Grant Application'), ('month_11', 'Month 11 - Final Business Assessment'), ('month_12', 'Month 12 - Graduation Assessment')], max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('skipped', 'Skipped')], default='not_started', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('household_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='households.householdprogram')),
            ],
            options={
                'ordering': ['milestone'],
                'unique_together': {('household_program', 'milestone')},
            },
        ),
    ]
