# Generated by Django 5.2.6 on 2025-09-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_upgmilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='assets',
            field=models.JSONField(blank=True, default=dict, help_text='Household assets as JSON'),
        ),
        migrations.AddField(
            model_name='household',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Household consent for program participation'),
        ),
        migrations.AddField(
            model_name='household',
            name='has_clean_water',
            field=models.BooleanField(default=False, help_text='Household has clean water access'),
        ),
        migrations.AddField(
            model_name='household',
            name='has_electricity',
            field=models.BooleanField(default=False, help_text='Household has electricity access'),
        ),
        migrations.AddField(
            model_name='household',
            name='location',
            field=models.CharField(blank=True, help_text='Location description (rural, urban, remote)', max_length=200),
        ),
        migrations.AddField(
            model_name='household',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly household income in KES', max_digits=10, null=True),
        ),
    ]
