# Generated by Django 5.2.6 on 2025-10-01 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_county_alter_village_saturation_and_more'),
        ('households', '0003_household_assets_household_consent_given_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='subcounty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='households', to='core.subcounty'),
        ),
    ]
