# Generated by Django 5.2.6 on 2025-10-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0004_household_subcounty'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='constituency',
            field=models.CharField(blank=True, help_text='Constituency', max_length=100),
        ),
        migrations.AddField(
            model_name='household',
            name='district',
            field=models.CharField(blank=True, help_text='District', max_length=100),
        ),
        migrations.AddField(
            model_name='household',
            name='division',
            field=models.CharField(blank=True, help_text='Division', max_length=100),
        ),
        migrations.AddField(
            model_name='household',
            name='head_date_of_birth',
            field=models.DateField(blank=True, help_text='Date of Birth of Household Head', null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='head_first_name',
            field=models.CharField(blank=True, help_text='First Name of Household Head', max_length=100),
        ),
        migrations.AddField(
            model_name='household',
            name='head_id_number',
            field=models.CharField(blank=True, help_text='ID Number of Household Head', max_length=50),
        ),
        migrations.AddField(
            model_name='household',
            name='head_last_name',
            field=models.CharField(blank=True, help_text='Last Name of Household Head', max_length=100),
        ),
        migrations.AddField(
            model_name='household',
            name='head_middle_name',
            field=models.CharField(blank=True, help_text='Middle Name of Household Head', max_length=100),
        ),
        migrations.AddField(
            model_name='household',
            name='head_phone_number',
            field=models.CharField(blank=True, help_text='Phone Number of Household Head', max_length=15),
        ),
        migrations.AddField(
            model_name='household',
            name='location_name',
            field=models.CharField(blank=True, help_text='Location', max_length=100),
        ),
        migrations.AddField(
            model_name='household',
            name='sub_location',
            field=models.CharField(blank=True, help_text='Sub Location', max_length=100),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of Birth', null=True),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='id_number',
            field=models.CharField(blank=True, help_text='National ID or Birth Certificate Number', max_length=50),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone Number', max_length=15),
        ),
        migrations.AlterField(
            model_name='household',
            name='name',
            field=models.CharField(help_text='Household name or identifier', max_length=100),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='age',
            field=models.IntegerField(help_text='Age in years'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='is_program_participant',
            field=models.BooleanField(default=False, help_text='Only household head can participate'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='name',
            field=models.CharField(help_text='Full name (for backward compatibility)', max_length=100),
        ),
    ]
