# Generated by Django 5.2.6 on 2025-09-24 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('program_type', models.CharField(choices=[('graduation', 'Ultra-Poor Graduation'), ('microfinance', 'Microfinance'), ('agricultural', 'Agricultural Support'), ('education', 'Education Support'), ('health', 'Health Initiative'), ('infrastructure', 'Infrastructure Development'), ('skills_training', 'Skills Training'), ('youth_empowerment', 'Youth Empowerment'), ('women_empowerment', 'Women Empowerment'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target_beneficiaries', models.PositiveIntegerField(default=0)),
                ('duration_months', models.PositiveIntegerField(default=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('eligibility_criteria', models.TextField(blank=True, help_text='Eligibility requirements for this program')),
                ('application_requirements', models.TextField(blank=True, help_text='Documents and requirements for application')),
                ('is_accepting_applications', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('motivation_letter', models.TextField(blank=True, help_text='Why the household wants to join this program')),
                ('additional_notes', models.TextField(blank=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_applications', to='households.household')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='programs.program')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-application_date'],
                'unique_together': {('program', 'household')},
            },
        ),
        migrations.CreateModel(
            name='ProgramBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participation_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('graduated', 'Graduated'), ('dropped_out', 'Dropped Out'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('enrollment_date', models.DateField()),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('progress_notes', models.TextField(blank=True)),
                ('benefits_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='independent_program_participations', to='households.household')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='programs.program')),
            ],
            options={
                'ordering': ['-enrollment_date'],
                'unique_together': {('program', 'household')},
            },
        ),
    ]
