# Generated by Django 5.2.6 on 2025-09-25 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_esrimport_esrimportrecord'),
        ('households', '0001_initial'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='assigned_mentor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='bm_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='core.businessmentorcycle'),
        ),
        migrations.AddField(
            model_name='training',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='max_households',
            field=models.IntegerField(default=25, help_text='Maximum households per training'),
        ),
        migrations.AddField(
            model_name='training',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
        migrations.CreateModel(
            name='HouseholdTrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateField()),
                ('enrollment_status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('dropped_out', 'Dropped Out'), ('transferred', 'Transferred')], default='enrolled', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_training_enrollment', to='households.household')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_households', to='training.training')),
            ],
            options={
                'db_table': 'upg_household_training_enrollments',
            },
        ),
        migrations.CreateModel(
            name='PhoneNudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nudge_type', models.CharField(choices=[('reminder', 'Training Reminder'), ('follow_up', 'Follow-up Call'), ('support', 'Support Call'), ('check_in', 'Regular Check-in'), ('business_advice', 'Business Advice')], max_length=20)),
                ('call_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(help_text='Call duration in minutes')),
                ('notes', models.TextField(blank=True)),
                ('successful_contact', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_nudges', to='households.household')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upg_phone_nudges',
            },
        ),
        migrations.CreateModel(
            name='MentoringReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('households_visited', models.IntegerField(default=0)),
                ('phone_nudges_made', models.IntegerField(default=0)),
                ('trainings_conducted', models.IntegerField(default=0)),
                ('new_households_enrolled', models.IntegerField(default=0)),
                ('key_activities', models.TextField(help_text='Key activities during the period')),
                ('challenges_faced', models.TextField(blank=True)),
                ('successes_achieved', models.TextField(blank=True)),
                ('next_period_plans', models.TextField(blank=True)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upg_mentoring_reports',
                'unique_together': {('mentor', 'reporting_period', 'period_start')},
            },
        ),
    ]
