# Generated by Django 5.2.6 on 2025-09-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_training_assigned_mentor_training_bm_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='time_taken',
            field=models.DurationField(blank=True, help_text='Training duration', null=True),
        ),
    ]
