# Generated by Django 5.2.6 on 2025-09-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_training_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='duration_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Training length in hours', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='location',
            field=models.CharField(blank=True, help_text='Training location/venue', max_length=200),
        ),
        migrations.AddField(
            model_name='training',
            name='module_number',
            field=models.IntegerField(blank=True, help_text='Sequential module number (1, 2, 3, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='participant_count',
            field=models.IntegerField(blank=True, help_text='Actual number of participants', null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='training_dates',
            field=models.JSONField(blank=True, default=list, help_text='List of specific training session dates'),
        ),
    ]
