# Generated by Django 5.2.6 on 2025-09-26 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_training_duration_hours_training_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingattendance',
            name='attendance_marked_at',
            field=models.DateTimeField(blank=True, help_text='When attendance was last updated', null=True),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, help_text='Mentor who marked this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL),
        ),
    ]
